######################################################################
# Automatically generated by qmake (2.01a) fr 16. mar 19:38:14 2007
######################################################################

TEMPLATE = app
TARGET = tcpclient
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += \
    ImageStream.h
SOURCES += \
    Main.cpp \
    ImageStream.cpp
QT += network widgets core gui qml quick serialport
CONFIG += console 

RESOURCES += \
    pic.qrc
